//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ItemStatus.
const (
	Allocated   ItemStatus = "allocated"
	Consigned   ItemStatus = "consigned"
	Quarantined ItemStatus = "quarantined"
	Staged      ItemStatus = "staged"
)

// Valid indicates whether the value is a known member of the ItemStatus enum.
func (e ItemStatus) Valid() bool {
	switch e {
	case Allocated:
		return true
	case Consigned:
		return true
	case Quarantined:
		return true
	case Staged:
		return true
	default:
		return false
	}
}

// Error A machine-readable error.
type Error struct {
	// Message What went wrong, for humans.
	Message string `json:"message"`
}

// Item A single stock item.
type Item struct {
	// Id The item's id.
	Id string `json:"id"`

	// Name The item's name.
	Name string `json:"name"`

	// Quantity How many units are on hand.
	Quantity int `json:"quantity"`

	// Status Where a stock item sits in the inventory workflow.
	Status ItemStatus `json:"status"`
}

// ItemList A page of stock items.
type ItemList struct {
	// Items The matching stock items.
	Items []Item `json:"items"`
}

// ItemStatus Where a stock item sits in the inventory workflow.
type ItemStatus string

// NewItem The fields needed to create a stock item.
type NewItem struct {
	// Name The item's name.
	Name string `json:"name"`

	// Quantity How many units are on hand.
	Quantity int `json:"quantity"`

	// Status Where a stock item sits in the inventory workflow.
	Status ItemStatus `json:"status"`
}

// ListInventoryItemsParams defines parameters for ListInventoryItems.
type ListInventoryItemsParams struct {
	// Status Restrict the result to items in this status.
	Status *ItemStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateInventoryItemJSONRequestBody defines body for CreateInventoryItem for application/json ContentType.
type CreateInventoryItemJSONRequestBody = NewItem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListInventoryItems List stock items, optionally filtered by status.
	// (GET /api/inventory/items)
	ListInventoryItems(w http.ResponseWriter, r *http.Request, params ListInventoryItemsParams)
	// CreateInventoryItem Create a stock item.
	// (POST /api/inventory/items)
	CreateInventoryItem(w http.ResponseWriter, r *http.Request)
	// GetInventoryItem Get one stock item by id.
	// (GET /api/inventory/items/{id})
	GetInventoryItem(w http.ResponseWriter, r *http.Request, id string)
	// GetInventorySpec Return this service's own OpenAPI contract.
	// (GET /openapi.yaml)
	GetInventorySpec(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListInventoryItems operation middleware
func (siw *ServerInterfaceWrapper) ListInventoryItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInventoryItemsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInventoryItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInventoryItem operation middleware
func (siw *ServerInterfaceWrapper) CreateInventoryItem(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInventoryItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInventoryItem operation middleware
func (siw *ServerInterfaceWrapper) GetInventoryItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInventoryItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInventorySpec operation middleware
func (siw *ServerInterfaceWrapper) GetInventorySpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInventorySpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/openapi.yaml", wrapper.GetInventorySpec)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/inventory/items", wrapper.ListInventoryItems)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/inventory/items", wrapper.CreateInventoryItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/inventory/items/{id}", wrapper.GetInventoryItem)

	return m
}

type ListInventoryItemsRequestObject struct {
	Params ListInventoryItemsParams
}

type ListInventoryItemsResponseObject interface {
	VisitListInventoryItemsResponse(w http.ResponseWriter) error
}

type ListInventoryItems200JSONResponse ItemList

func (response ListInventoryItems200JSONResponse) VisitListInventoryItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInventoryItemRequestObject struct {
	Body *CreateInventoryItemJSONRequestBody
}

type CreateInventoryItemResponseObject interface {
	VisitCreateInventoryItemResponse(w http.ResponseWriter) error
}

type CreateInventoryItem201JSONResponse Item

func (response CreateInventoryItem201JSONResponse) VisitCreateInventoryItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type GetInventoryItemRequestObject struct {
	Id string `json:"id"`
}

type GetInventoryItemResponseObject interface {
	VisitGetInventoryItemResponse(w http.ResponseWriter) error
}

type GetInventoryItem200JSONResponse Item

func (response GetInventoryItem200JSONResponse) VisitGetInventoryItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInventoryItem404JSONResponse Error

func (response GetInventoryItem404JSONResponse) VisitGetInventoryItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInventorySpecRequestObject struct {
}

type GetInventorySpecResponseObject interface {
	VisitGetInventorySpecResponse(w http.ResponseWriter) error
}

type GetInventorySpec200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetInventorySpec200ApplicationyamlResponse) VisitGetInventorySpecResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListInventoryItems List stock items, optionally filtered by status.
	// (GET /api/inventory/items)
	ListInventoryItems(ctx context.Context, request ListInventoryItemsRequestObject) (ListInventoryItemsResponseObject, error)
	// CreateInventoryItem Create a stock item.
	// (POST /api/inventory/items)
	CreateInventoryItem(ctx context.Context, request CreateInventoryItemRequestObject) (CreateInventoryItemResponseObject, error)
	// GetInventoryItem Get one stock item by id.
	// (GET /api/inventory/items/{id})
	GetInventoryItem(ctx context.Context, request GetInventoryItemRequestObject) (GetInventoryItemResponseObject, error)
	// GetInventorySpec Return this service's own OpenAPI contract.
	// (GET /openapi.yaml)
	GetInventorySpec(ctx context.Context, request GetInventorySpecRequestObject) (GetInventorySpecResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListInventoryItems operation middleware
func (sh *strictHandler) ListInventoryItems(w http.ResponseWriter, r *http.Request, params ListInventoryItemsParams) {
	var request ListInventoryItemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInventoryItems(ctx, request.(ListInventoryItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInventoryItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInventoryItemsResponseObject); ok {
		if err := validResponse.VisitListInventoryItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInventoryItem operation middleware
func (sh *strictHandler) CreateInventoryItem(w http.ResponseWriter, r *http.Request) {
	var request CreateInventoryItemRequestObject

	var body CreateInventoryItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInventoryItem(ctx, request.(CreateInventoryItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInventoryItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInventoryItemResponseObject); ok {
		if err := validResponse.VisitCreateInventoryItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInventoryItem operation middleware
func (sh *strictHandler) GetInventoryItem(w http.ResponseWriter, r *http.Request, id string) {
	var request GetInventoryItemRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInventoryItem(ctx, request.(GetInventoryItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInventoryItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInventoryItemResponseObject); ok {
		if err := validResponse.VisitGetInventoryItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInventorySpec operation middleware
func (sh *strictHandler) GetInventorySpec(w http.ResponseWriter, r *http.Request) {
	var request GetInventorySpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInventorySpec(ctx, request.(GetInventorySpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInventorySpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInventorySpecResponseObject); ok {
		if err := validResponse.VisitGetInventorySpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5JdRaxvHFse/ymHuhXsLa8lp/LRvbhISQZqGOlBK6ofj3SPtxLsz65lZy4sRNA4keWioIaQlkEJaQptS",
	"CIEWmpiEfBhZtvMtysxKq5V27STgPPVJK3nnzJn/+c3/HG+zQCapFCSMZv4200FECbrHC0pJZR9C0oHi",
	"qeFSMJ8tQ4JBxAUtKMIQ12ICsm+2mMdSJVNShpMLkJDW2KN6iK8iNNAnYaCvpOh50JUKoixBoW0Uk6fE",
	"fKaN4qLHBgOPKdrIuKKQ+dfLqKvli3LtBgWGDTzWMZQ0Zay56MUE2shgHbihpJ4sD+sLr0Xk3v6fBh66",
	"zLiJ7Y6d8/U0PSYwoROD2BeqYUb3b4527zWF2shQGG7yerhLsg8JihwywY0GVARSQIRiJsGDB8/f3vl+",
	"GpkLQz1SNrQ2aDJ35P8q6jKf/ac9RaA9rn/bKrlSvDlfAB6y8VnLYJWEjyvLZa5NU2lS7BHIbqU2uqE4",
	"9udmaRM0lsbefIByybtOyQZlxqgU5vXzukjHnWullHOecVIEWEkLtC0YF2AsEWKThJEqh75U691Y9m3S",
	"JLLEbolxLAM0FBYS99zDRobKiizct0AKzXv2eXVa9uHOy+Gt28Nbr4Y7b4Y7L2tkeWxrwe6xEOMaxS7r",
	"6VY+G716MHp9/+DF3Zn4Pnv7ePfo6Y+jR09He3/MJeKzgyePRvdv7r/56fDBw2m6Phvd2Tu69/fB3g+j",
	"nYejZ9/t7912yl6hfvMttcXscopDDYIopBCMhEARmlkZ63T8S+7dB1w5u5SLrqwf43yWJHmFPk1qkwfk",
	"z1wfuLDFtdGgpWNVqiAibRTaGJDGaLpSJRChBgRFGAOJMJVcGFuyNEYB2EMutGnBChGEMtBtnVKg2zOh",
	"WknY+kZUbbVMa/lqh3lsk5Qu0l5snWktOnwzvhBxUVgJ12mM+RVXflbgefjs58PdgjSZksCUM5+dbS22",
	"zlps0ESuAm1MebsUoV16RY8aPOpLMpkSGmiTVF7RCdaF7AswhUhjIVtguZNuLcZQFAs2Mrs0RYUJGVIg",
	"UCnZ126hIp3FTjmXRmEQaMZLC4Es7U6yjr1Z1kpLqToud4+VwTXzr9ePYBEPzPEbcj3ZkFl0mM9czhOn",
	"96fYFaR+EMerFmSdSqGLC/vp4qL9CKQwVJQS0zTmgTti+4aWYjqKvM9Grrc46N+3P9h3dZYkqPKxoNW/",
	"e2UB4xy6PDakKIS1vCKRwZ6eaQ5bCyXbC7SVSk3MNyqj92B2/8W3R7/+5nJKZWOXDEN71QT1q/jNgmdn",
	"FLGQUCILSBW1oGPs4AJcA+rCzO0hqrQ20HXOWe4MX6wwItLmMxnmp1a6SSsYzDqdVW1QI+bMqRJzHC1F",
	"vwln2s0sK+eaO9Jp8jDc+WW488Q18sfDm8/2Xz86uLtbZNxkXO1tHg7e6V5YH4I9kAqWFpegH9F4KnGw",
	"ZMI5W6uGxkUy81ycaDu1+dkZi3Xhqa+4aXK2+FWPOWni/ui+chwl48swz4nHlhaXTi2B4t+vhgyuFMYN",
	"VDTpPjdRYeBW41lYL5IBKao1twbAw49M7NHvfx7+9XxM7LgNt3JM4mMpXSG1aeUsLK0cMQIU0CUTRO5n",
	"K6vCwIDcJAWXrl27Cv/nxtkbpEoGpLUHQhpAa9puPkPQEVrzDrle/wRQhLCW8TgEbjQEaDCWvYygq2QC",
	"3DTZYZX5lZQC9kHMTQ5dAXqO4UbApp7+RUpi+WrHzlBZQsJ4gBq+Xv788nypi3s+7uTlcjugTEJM5KsW",
	"X+facr7q8rDLTrjI8zOj+yTtpLT72D2swJPv1f0yFTOftdlgtdy7hsC0/0JEcdmqavu2KuZh32YDb/tE",
	"DeeTGS8en32wOvhnAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
