//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Component.
const (
	ComponentChoice Component = "choice"
	ComponentDetail Component = "detail"
	ComponentForm   Component = "form"
	ComponentTable  Component = "table"
)

// Valid indicates whether the value is a known member of the Component enum.
func (e Component) Valid() bool {
	switch e {
	case ComponentChoice:
		return true
	case ComponentDetail:
		return true
	case ComponentForm:
		return true
	case ComponentTable:
		return true
	default:
		return false
	}
}

// Defines values for DecisionKind.
const (
	DecisionKindAsk    DecisionKind = "ask"
	DecisionKindForm   DecisionKind = "form"
	DecisionKindNone   DecisionKind = "none"
	DecisionKindResult DecisionKind = "result"
)

// Valid indicates whether the value is a known member of the DecisionKind enum.
func (e DecisionKind) Valid() bool {
	switch e {
	case DecisionKindAsk:
		return true
	case DecisionKindForm:
		return true
	case DecisionKindNone:
		return true
	case DecisionKindResult:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleUser:
		return true
	default:
		return false
	}
}

// Answer The user's answer to a previous `kind: ask` response, resubmitted alongside the original query.
type Answer struct {
	// Param The parameter name the value fills in.
	Param string `json:"param"`

	// Value The chosen value.
	Value string `json:"value"`
}

// Component The widget the frontend renders the result with.
type Component string

// CreatePanelRequest A call to save as a new panel, appended after this workspace's others.
type CreatePanelRequest struct {
	// Args The call's arguments.
	Args map[string]interface{} `json:"args"`

	// Component The widget the frontend renders the result with.
	Component Component `json:"component"`

	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`

	// Title The panel's title. Left blank, the panel is titled with its operation id instead of showing an empty card header.
	Title string `json:"title"`
}

// CreateWorkspaceRequest A new, empty workspace.
type CreateWorkspaceRequest struct {
	// Name The workspace's name.
	Name string `json:"name"`
}

// DecisionKind What the planner decided to do about a question.
type DecisionKind string

// ErrorResponse A machine-readable error.
type ErrorResponse struct {
	// Message What went wrong, for humans.
	Message string `json:"message"`
}

// Health The platform's health status.
type Health struct {
	// Status Always "ok" once the process is serving traffic.
	Status string `json:"status"`
}

// InvokeRequest A confirmed call to execute.
type InvokeRequest struct {
	// Args The call's arguments.
	Args map[string]interface{} `json:"args"`

	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`
}

// InvokeResult A call's rendered result.
type InvokeResult struct {
	// Component The widget the frontend renders the result with.
	Component Component `json:"component"`

	// Data The rendered result.
	Data map[string]interface{} `json:"data"`

	// Fields Per-property JSON Schema for `data`'s columns (`table`) or own properties (`detail`) - the same shape as `PlanResult.fields`, built the same way, so a detail turn appended after a form submission shows a Japanese title and enum label exactly like a `/api/plan` result does. Absent when the result has no columns to describe (not an empty object).
	Fields *map[string]interface{} `json:"fields,omitempty"`
}

// Operation One operation the catalogue holds - a service and operation id, with its summary, for the admin's permission grid (docs/specs/auth.md, section 4). GET /api/operations lists every one of these; Permission names which of them one account may call.
type Operation struct {
	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`

	// Summary The operation's summary, from its contract.
	Summary *string `json:"summary,omitempty"`
}

// Option One candidate value the user can pick, with its Japanese label.
type Option struct {
	// Label Its Japanese label (from x-enum-labels).
	Label string `json:"label"`

	// Value The enum value.
	Value string `json:"value"`
}

// Panel A saved call: everything a plan result's source and component already carry, plus a title and a position (docs/specs/workspaces.md, section 3). No panel carries its answer - opening a workspace re-runs each panel's call through /api/invoke instead (W2).
type Panel struct {
	// Args The call's arguments.
	Args map[string]interface{} `json:"args"`

	// Component The widget the frontend renders the result with.
	Component Component `json:"component"`

	// Id The panel's id, assigned by the platform.
	Id string `json:"id"`

	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Position Where the panel sits among its workspace's others, ascending. Not editable in this slice (W5).
	Position int `json:"position"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`

	// Title The panel's title. A person can edit it; left blank when saved, it defaults to the operation id.
	Title string `json:"title"`

	// WorkspaceId The workspace this panel belongs to.
	WorkspaceId string `json:"workspaceId"`
}

// Permission One operation a person may call (docs/specs/auth.md, section 4, A3). A row says this person may call this operation; there is no deny, because there is nothing to override.
type Permission struct {
	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`
}

// PlanRequest A question, any answers to a previous disambiguation, and the conversation before it.
type PlanRequest struct {
	// Answers Answers to a previous `kind: ask` response, if any.
	Answers *[]Answer `json:"answers,omitempty"`

	// Query The question, in Japanese.
	Query string `json:"query"`

	// Turns The conversation so far, oldest first. Absent or empty means what it means today: a question with no history (docs/specs/context.md, section 5).
	Turns *[]Turn `json:"turns,omitempty"`
}

// PlanResult The planner's decision and, when it was safe to act on immediately, its result. Which of the optional fields are present depends on `kind`: `result` carries `component`, `data`, `source` and, when the response has columns to describe, `fields`; `form` carries `schema`, `initial` and `target`; `ask` carries `question`, `param` and `options`; `none` carries `message`.
type PlanResult struct {
	// Component The widget the frontend renders the result with.
	Component *Component `json:"component,omitempty"`

	// Data The rendered result, when kind is "result".
	Data *map[string]interface{} `json:"data,omitempty"`

	// Fields Per-property JSON Schema for `data`'s columns (`table`) or own properties (`detail`), when kind is "result" - most importantly each enum property's `enumLabels` (value -> Japanese label), so a table cell or form control can show "検品保留" instead of "quarantined" without parsing a model-facing description string apart. Absent when the result has no columns to describe (not an empty object).
	Fields *map[string]interface{} `json:"fields,omitempty"`

	// Initial The values the planner filled in, when kind is "form".
	Initial *map[string]interface{} `json:"initial,omitempty"`

	// Kind What the planner decided to do about a question.
	Kind DecisionKind `json:"kind"`

	// Message A human-readable explanation, when kind is "none".
	Message *string `json:"message,omitempty"`

	// Options The candidate values to choose from, when kind is "ask".
	Options *[]Option `json:"options,omitempty"`

	// Param The parameter the answer will fill in, when kind is "ask".
	Param *string `json:"param,omitempty"`

	// Question The question to show the user, when kind is "ask".
	Question *string `json:"question,omitempty"`

	// Schema The request body's JSON Schema, when kind is "form".
	Schema *map[string]interface{} `json:"schema,omitempty"`

	// Source Which endpoint of which service a call was, or would be, made against.
	Source *Source `json:"source,omitempty"`

	// Target Which endpoint of which service a call was, or would be, made against.
	Target *Source `json:"target,omitempty"`
}

// Role What an account may do beyond the permissions it holds individually (docs/specs/auth.md, A5). An admin may read every account and set anybody's permissions; that is the whole of what the role buys.
type Role string

// SetUserPermissionsRequest The whole set of permissions an account should hold, replacing whatever it held before (usecase.PermissionStore.Set).
type SetUserPermissionsRequest struct {
	Permissions []Permission `json:"permissions"`
}

// SignInRequest A name and password to check against the platform's accounts.
type SignInRequest struct {
	// Name The account's name.
	Name string `json:"name"`

	// Password The account's password, in the clear over the wire (HTTPS carries it) - never stored this way (docs/specs/auth.md, section 3).
	Password string `json:"password"`
}

// Source Which endpoint of which service a call was, or would be, made against.
type Source struct {
	// Args The arguments the planner (or the user) supplied.
	Args *map[string]interface{} `json:"args,omitempty"`

	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`
}

// Turn One earlier question in the conversation, and what the platform decided for it - never the answer's data (docs/specs/context.md, section 3). `PlanRequest.turns` carries these oldest first.
type Turn struct {
	// Args The arguments the decision was made with.
	Args *map[string]interface{} `json:"args,omitempty"`

	// Kind What the planner decided to do about a question.
	Kind DecisionKind `json:"kind"`

	// OperationId The operation id the decision named. Absent when kind is "none".
	OperationId *string `json:"operationId,omitempty"`

	// Question The question, in Japanese, as it was asked.
	Question string `json:"question"`

	// Service The service the decision named. Absent when kind is "none".
	Service *string `json:"service,omitempty"`
}

// User A signed-in account (docs/specs/auth.md, section 3).
type User struct {
	// Id The account's id, assigned by the platform.
	Id string `json:"id"`

	// Name What the person types to sign in.
	Name string `json:"name"`

	// Role What an account may do beyond the permissions it holds individually (docs/specs/auth.md, A5). An admin may read every account and set anybody's permissions; that is the whole of what the role buys.
	Role Role `json:"role"`
}

// Workspace One workspace and its panels, in position order.
type Workspace struct {
	// Id The workspace's id, assigned by the platform.
	Id string `json:"id"`

	// Name The workspace's name.
	Name string `json:"name"`

	// Panels The workspace's panels, in position order.
	Panels []Panel `json:"panels"`
}

// WorkspaceCreated The workspace just created.
type WorkspaceCreated struct {
	// Id The workspace's id, assigned by the platform.
	Id string `json:"id"`

	// Name The workspace's name.
	Name string `json:"name"`
}

// WorkspaceSummary One row of the workspaces list - no panel data, only a count.
type WorkspaceSummary struct {
	// Id The workspace's id, assigned by the platform.
	Id string `json:"id"`

	// Name The workspace's name.
	Name string `json:"name"`

	// PanelCount How many panels the workspace holds.
	PanelCount int `json:"panelCount"`
}

// PostInvokeJSONRequestBody defines body for PostInvoke for application/json ContentType.
type PostInvokeJSONRequestBody = InvokeRequest

// PostPlanJSONRequestBody defines body for PostPlan for application/json ContentType.
type PostPlanJSONRequestBody = PlanRequest

// PostSessionJSONRequestBody defines body for PostSession for application/json ContentType.
type PostSessionJSONRequestBody = SignInRequest

// SetUserPermissionsJSONRequestBody defines body for SetUserPermissions for application/json ContentType.
type SetUserPermissionsJSONRequestBody = SetUserPermissionsRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// AddPanelJSONRequestBody defines body for AddPanel for application/json ContentType.
type AddPanelJSONRequestBody = CreatePanelRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Report whether the platform is up.
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// PostInvoke Execute a confirmed call against a service.
	// (POST /api/invoke)
	PostInvoke(w http.ResponseWriter, r *http.Request)
	// ListOperations List every operation across every configured service.
	// (GET /api/operations)
	ListOperations(w http.ResponseWriter, r *http.Request)
	// PostPlan Turn a question into a decision and, when safe, its result.
	// (POST /api/plan)
	PostPlan(w http.ResponseWriter, r *http.Request)
	// DeleteSession Sign out.
	// (DELETE /api/session)
	DeleteSession(w http.ResponseWriter, r *http.Request)
	// GetSession Who is signed in.
	// (GET /api/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// PostSession Sign in.
	// (POST /api/session)
	PostSession(w http.ResponseWriter, r *http.Request)
	// ListUsers List every account.
	// (GET /api/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// GetUserPermissions Read one account's permissions.
	// (GET /api/users/{id}/permissions)
	GetUserPermissions(w http.ResponseWriter, r *http.Request, id string)
	// SetUserPermissions Replace one account's permissions, wholesale.
	// (PUT /api/users/{id}/permissions)
	SetUserPermissions(w http.ResponseWriter, r *http.Request, id string)
	// ListWorkspaces List the stub owner's workspaces.
	// (GET /api/workspaces)
	ListWorkspaces(w http.ResponseWriter, r *http.Request)
	// CreateWorkspace Create an empty workspace.
	// (POST /api/workspaces)
	CreateWorkspace(w http.ResponseWriter, r *http.Request)
	// DeleteWorkspace Delete a workspace and every panel it holds.
	// (DELETE /api/workspaces/{id})
	DeleteWorkspace(w http.ResponseWriter, r *http.Request, id string)
	// GetWorkspace Read one workspace and its panels, in position order.
	// (GET /api/workspaces/{id})
	GetWorkspace(w http.ResponseWriter, r *http.Request, id string)
	// AddPanel Save a call as a panel on a workspace.
	// (POST /api/workspaces/{id}/panels)
	AddPanel(w http.ResponseWriter, r *http.Request, id string)
	// DeletePanel Remove one panel from a workspace.
	// (DELETE /api/workspaces/{id}/panels/{panelId})
	DeletePanel(w http.ResponseWriter, r *http.Request, id string, panelId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostInvoke operation middleware
func (siw *ServerInterfaceWrapper) PostInvoke(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostInvoke(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOperations operation middleware
func (siw *ServerInterfaceWrapper) ListOperations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOperations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPlan operation middleware
func (siw *ServerInterfaceWrapper) PostPlan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPlan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSession operation middleware
func (siw *ServerInterfaceWrapper) PostSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetUserPermissions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserPermissions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetUserPermissions operation middleware
func (siw *ServerInterfaceWrapper) SetUserPermissions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetUserPermissions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) ListWorkspaces(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkspaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWorkspace operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkspace(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkspace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWorkspace operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkspace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPanel operation middleware
func (siw *ServerInterfaceWrapper) AddPanel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPanel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePanel operation middleware
func (siw *ServerInterfaceWrapper) DeletePanel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "panelId" -------------
	var panelId string

	err = runtime.BindStyledParameterWithOptions("simple", "panelId", r.PathValue("panelId"), &panelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "panelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePanel(w, r, id, panelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/session", wrapper.DeleteSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/session", wrapper.GetSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/session", wrapper.PostSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/plan", wrapper.PostPlan)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/invoke", wrapper.PostInvoke)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/workspaces", wrapper.ListWorkspaces)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/workspaces", wrapper.CreateWorkspace)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/workspaces/{id}", wrapper.DeleteWorkspace)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/workspaces/{id}", wrapper.GetWorkspace)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/workspaces/{id}/panels", wrapper.AddPanel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/workspaces/{id}/panels/{panelId}", wrapper.DeletePanel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/users/{id}/permissions", wrapper.GetUserPermissions)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/users/{id}/permissions", wrapper.SetUserPermissions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/operations", wrapper.ListOperations)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostInvokeRequestObject struct {
	Body *PostInvokeJSONRequestBody
}

type PostInvokeResponseObject interface {
	VisitPostInvokeResponse(w http.ResponseWriter) error
}

type PostInvoke200JSONResponse InvokeResult

func (response PostInvoke200JSONResponse) VisitPostInvokeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostInvoke400JSONResponse ErrorResponse

func (response PostInvoke400JSONResponse) VisitPostInvokeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostInvoke500JSONResponse ErrorResponse

func (response PostInvoke500JSONResponse) VisitPostInvokeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListOperationsRequestObject struct {
}

type ListOperationsResponseObject interface {
	VisitListOperationsResponse(w http.ResponseWriter) error
}

type ListOperations200JSONResponse []Operation

func (response ListOperations200JSONResponse) VisitListOperationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOperations403JSONResponse ErrorResponse

func (response ListOperations403JSONResponse) VisitListOperationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostPlanRequestObject struct {
	Body *PostPlanJSONRequestBody
}

type PostPlanResponseObject interface {
	VisitPostPlanResponse(w http.ResponseWriter) error
}

type PostPlan200JSONResponse PlanResult

func (response PostPlan200JSONResponse) VisitPostPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostPlan500JSONResponse ErrorResponse

func (response PostPlan500JSONResponse) VisitPostPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostPlan501JSONResponse ErrorResponse

func (response PostPlan501JSONResponse) VisitPostPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionRequestObject struct {
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetSessionRequestObject struct {
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse User

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSession401JSONResponse ErrorResponse

func (response GetSession401JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostSessionRequestObject struct {
	Body *PostSessionJSONRequestBody
}

type PostSessionResponseObject interface {
	VisitPostSessionResponse(w http.ResponseWriter) error
}

type PostSession200JSONResponse User

func (response PostSession200JSONResponse) VisitPostSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostSession401JSONResponse ErrorResponse

func (response PostSession401JSONResponse) VisitPostSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse []User

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsers403JSONResponse ErrorResponse

func (response ListUsers403JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserPermissionsRequestObject struct {
	Id string `json:"id"`
}

type GetUserPermissionsResponseObject interface {
	VisitGetUserPermissionsResponse(w http.ResponseWriter) error
}

type GetUserPermissions200JSONResponse []Permission

func (response GetUserPermissions200JSONResponse) VisitGetUserPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserPermissions403JSONResponse ErrorResponse

func (response GetUserPermissions403JSONResponse) VisitGetUserPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SetUserPermissionsRequestObject struct {
	Id   string `json:"id"`
	Body *SetUserPermissionsJSONRequestBody
}

type SetUserPermissionsResponseObject interface {
	VisitSetUserPermissionsResponse(w http.ResponseWriter) error
}

type SetUserPermissions204Response struct {
}

func (response SetUserPermissions204Response) VisitSetUserPermissionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetUserPermissions403JSONResponse ErrorResponse

func (response SetUserPermissions403JSONResponse) VisitSetUserPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkspacesRequestObject struct {
}

type ListWorkspacesResponseObject interface {
	VisitListWorkspacesResponse(w http.ResponseWriter) error
}

type ListWorkspaces200JSONResponse []WorkspaceSummary

func (response ListWorkspaces200JSONResponse) VisitListWorkspacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWorkspaceRequestObject struct {
	Body *CreateWorkspaceJSONRequestBody
}

type CreateWorkspaceResponseObject interface {
	VisitCreateWorkspaceResponse(w http.ResponseWriter) error
}

type CreateWorkspace201JSONResponse WorkspaceCreated

func (response CreateWorkspace201JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorkspaceRequestObject struct {
	Id string `json:"id"`
}

type DeleteWorkspaceResponseObject interface {
	VisitDeleteWorkspaceResponse(w http.ResponseWriter) error
}

type DeleteWorkspace204Response struct {
}

func (response DeleteWorkspace204Response) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetWorkspaceRequestObject struct {
	Id string `json:"id"`
}

type GetWorkspaceResponseObject interface {
	VisitGetWorkspaceResponse(w http.ResponseWriter) error
}

type GetWorkspace200JSONResponse Workspace

func (response GetWorkspace200JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWorkspace404JSONResponse ErrorResponse

func (response GetWorkspace404JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AddPanelRequestObject struct {
	Id   string `json:"id"`
	Body *AddPanelJSONRequestBody
}

type AddPanelResponseObject interface {
	VisitAddPanelResponse(w http.ResponseWriter) error
}

type AddPanel201JSONResponse Panel

func (response AddPanel201JSONResponse) VisitAddPanelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AddPanel400JSONResponse ErrorResponse

func (response AddPanel400JSONResponse) VisitAddPanelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AddPanel404JSONResponse ErrorResponse

func (response AddPanel404JSONResponse) VisitAddPanelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeletePanelRequestObject struct {
	Id      string `json:"id"`
	PanelId string `json:"panelId"`
}

type DeletePanelResponseObject interface {
	VisitDeletePanelResponse(w http.ResponseWriter) error
}

type DeletePanel204Response struct {
}

func (response DeletePanel204Response) VisitDeletePanelResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Report whether the platform is up.
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// PostInvoke Execute a confirmed call against a service.
	// (POST /api/invoke)
	PostInvoke(ctx context.Context, request PostInvokeRequestObject) (PostInvokeResponseObject, error)
	// ListOperations List every operation across every configured service.
	// (GET /api/operations)
	ListOperations(ctx context.Context, request ListOperationsRequestObject) (ListOperationsResponseObject, error)
	// PostPlan Turn a question into a decision and, when safe, its result.
	// (POST /api/plan)
	PostPlan(ctx context.Context, request PostPlanRequestObject) (PostPlanResponseObject, error)
	// DeleteSession Sign out.
	// (DELETE /api/session)
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// GetSession Who is signed in.
	// (GET /api/session)
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// PostSession Sign in.
	// (POST /api/session)
	PostSession(ctx context.Context, request PostSessionRequestObject) (PostSessionResponseObject, error)
	// ListUsers List every account.
	// (GET /api/users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// GetUserPermissions Read one account's permissions.
	// (GET /api/users/{id}/permissions)
	GetUserPermissions(ctx context.Context, request GetUserPermissionsRequestObject) (GetUserPermissionsResponseObject, error)
	// SetUserPermissions Replace one account's permissions, wholesale.
	// (PUT /api/users/{id}/permissions)
	SetUserPermissions(ctx context.Context, request SetUserPermissionsRequestObject) (SetUserPermissionsResponseObject, error)
	// ListWorkspaces List the stub owner's workspaces.
	// (GET /api/workspaces)
	ListWorkspaces(ctx context.Context, request ListWorkspacesRequestObject) (ListWorkspacesResponseObject, error)
	// CreateWorkspace Create an empty workspace.
	// (POST /api/workspaces)
	CreateWorkspace(ctx context.Context, request CreateWorkspaceRequestObject) (CreateWorkspaceResponseObject, error)
	// DeleteWorkspace Delete a workspace and every panel it holds.
	// (DELETE /api/workspaces/{id})
	DeleteWorkspace(ctx context.Context, request DeleteWorkspaceRequestObject) (DeleteWorkspaceResponseObject, error)
	// GetWorkspace Read one workspace and its panels, in position order.
	// (GET /api/workspaces/{id})
	GetWorkspace(ctx context.Context, request GetWorkspaceRequestObject) (GetWorkspaceResponseObject, error)
	// AddPanel Save a call as a panel on a workspace.
	// (POST /api/workspaces/{id}/panels)
	AddPanel(ctx context.Context, request AddPanelRequestObject) (AddPanelResponseObject, error)
	// DeletePanel Remove one panel from a workspace.
	// (DELETE /api/workspaces/{id}/panels/{panelId})
	DeletePanel(ctx context.Context, request DeletePanelRequestObject) (DeletePanelResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostInvoke operation middleware
func (sh *strictHandler) PostInvoke(w http.ResponseWriter, r *http.Request) {
	var request PostInvokeRequestObject

	var body PostInvokeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostInvoke(ctx, request.(PostInvokeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostInvoke")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostInvokeResponseObject); ok {
		if err := validResponse.VisitPostInvokeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOperations operation middleware
func (sh *strictHandler) ListOperations(w http.ResponseWriter, r *http.Request) {
	var request ListOperationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOperations(ctx, request.(ListOperationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOperations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOperationsResponseObject); ok {
		if err := validResponse.VisitListOperationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPlan operation middleware
func (sh *strictHandler) PostPlan(w http.ResponseWriter, r *http.Request) {
	var request PostPlanRequestObject

	var body PostPlanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPlan(ctx, request.(PostPlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPlanResponseObject); ok {
		if err := validResponse.VisitPostPlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request) {
	var request GetSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSession operation middleware
func (sh *strictHandler) PostSession(w http.ResponseWriter, r *http.Request) {
	var request PostSessionRequestObject

	var body PostSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSession(ctx, request.(PostSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSessionResponseObject); ok {
		if err := validResponse.VisitPostSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	var request ListUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserPermissions operation middleware
func (sh *strictHandler) GetUserPermissions(w http.ResponseWriter, r *http.Request, id string) {
	var request GetUserPermissionsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserPermissions(ctx, request.(GetUserPermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserPermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserPermissionsResponseObject); ok {
		if err := validResponse.VisitGetUserPermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetUserPermissions operation middleware
func (sh *strictHandler) SetUserPermissions(w http.ResponseWriter, r *http.Request, id string) {
	var request SetUserPermissionsRequestObject

	request.Id = id

	var body SetUserPermissionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetUserPermissions(ctx, request.(SetUserPermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetUserPermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetUserPermissionsResponseObject); ok {
		if err := validResponse.VisitSetUserPermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWorkspaces operation middleware
func (sh *strictHandler) ListWorkspaces(w http.ResponseWriter, r *http.Request) {
	var request ListWorkspacesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWorkspaces(ctx, request.(ListWorkspacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWorkspaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWorkspacesResponseObject); ok {
		if err := validResponse.VisitListWorkspacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWorkspace operation middleware
func (sh *strictHandler) CreateWorkspace(w http.ResponseWriter, r *http.Request) {
	var request CreateWorkspaceRequestObject

	var body CreateWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkspace(ctx, request.(CreateWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateWorkspaceResponseObject); ok {
		if err := validResponse.VisitCreateWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWorkspace operation middleware
func (sh *strictHandler) DeleteWorkspace(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteWorkspaceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorkspace(ctx, request.(DeleteWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteWorkspaceResponseObject); ok {
		if err := validResponse.VisitDeleteWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspace operation middleware
func (sh *strictHandler) GetWorkspace(w http.ResponseWriter, r *http.Request, id string) {
	var request GetWorkspaceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspace(ctx, request.(GetWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkspaceResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddPanel operation middleware
func (sh *strictHandler) AddPanel(w http.ResponseWriter, r *http.Request, id string) {
	var request AddPanelRequestObject

	request.Id = id

	var body AddPanelJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddPanel(ctx, request.(AddPanelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddPanel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddPanelResponseObject); ok {
		if err := validResponse.VisitAddPanelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePanel operation middleware
func (sh *strictHandler) DeletePanel(w http.ResponseWriter, r *http.Request, id string, panelId string) {
	var request DeletePanelRequestObject

	request.Id = id
	request.PanelId = panelId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePanel(ctx, request.(DeletePanelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePanel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePanelResponseObject); ok {
		if err := validResponse.VisitDeletePanelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7HzdjhvJdf+rHPT/D2gG6OHMrrS5oK4msrCSo6wUzWyEwBLCmu5DsjzdVdyq6qGIxQDeGAmC3MSAYQQB",
	"HCMGchEbQRDECeCLBHkY2d7NWwTnVPUXWU1yNtJ4ZeRKGrJZdep8f/yqP08yXS60QuVsMv48sdkcS8H/",
	"PVV2iYb+l6PNjFw4qVUyTs7nCJVFc8eC4EfAaRCwMHgldWVhcilVPgZhLydg0C60spjS/6qLUjqHOYhC",
	"q5mVOYKbI2gjZ1KJAj6r0KxGL1WSJgujF2icRKZkIYwo44TwV+jQgBKlX+9KFBXCVBaFBalGSZq41QKT",
	"cWKdkWqWXKcJPxJfMJtri8ovEvntdZoY/KySBvNk/J1AWb3gq+ZxffFdzBxt9aBmb3y7pcxn6JjuqdHK",
	"ocrBoMrRWP6Q2FY4WEo3J2pQVSXt68RFgUma5OiELJI0mWpDdGRzLbMuIYHuNHl9RL89KsQFFszU8Og4",
	"+e8vfvmbv/pJu9g4+epnv/jy3/6lXnWcvPn+j9782c/efP8/3nz/75M0bD5OvvrpPzJDHhgUDp8JhcVz",
	"/KxCGznrKWSiKEhTrLhCEBYEKFzCgn6Vglgs6NA5iCnJ0s2lhaU2l3YhMrxjQbs5Gjva0AxhZv7fPJe0",
	"kyiedb53psI0JmNRFKS9ZlaVpPijJCK4rCu4/29wmoyT/3fcfGqPg6kctxK+ThPaXNBWj/O4wJsHQOYp",
	"8SHHrBAGc5AK3Fw4sGiuJJ8608oZkbmoDofH4ru0a5BZ8D6ZVlM5q8JOT58/ePTw7Pz56Z+ePXz+x48f",
	"PDyLbuKkK3DI8hQSF/mRETzBqYOLQqjLFFz9Ncjwfc4aDNLZHgNAKutQ5KCnYOd6KdUMhAIsF24FmTA5",
	"zFHkaLxT2G6KNT/6Mki9inTFWZ8qaq2syi9qzduizgqXaSC0UdRN/STuDxh+R7vpqd2+hteKEf0tzKSV",
	"Wv2BVBGle0E6xRIphFJoSOEkmZrTkGsQF7pyIIAPKrXqehnvfFrvIuxlkiZKq/08DD0+Tr76xc9//aO/",
	"HnQmvBq5nH/99X/+8M0XP3/zxd8kab3zOPny33/wm5/8mHnx0BhtnoeAEhNJKbK5VHhkUOTkogDpF5tC",
	"KdFaMcMBVi1ROVgarWYpTLWBeVUKZXeLp141JqFHKAo3H7CjQjhizR1Lyl64OVgnXBVxdv7zyMmLpVhZ",
	"eJnoy5cJaJX5OLgwOkNryQbZNtQMnBHTqcx2HyZsFTvLY3WlL7dZBjsaU2LeuHx8jVnl8Fbd9++UI76J",
	"q9smM29U8dh8x4bEA/OQdWzK6+vFxFw4cXMpR4jZONdUYpHfUIOeoTkKp1rBt8+efgJnTDQb+4RonbDE",
	"i6pUFg4mnO1MDkEb0EsFLUPgYOIzpskhHLHFWUpB7VwsOMGZPCuE8jwfeUInKVxUsnDtw0uxSsFqEOCX",
	"AlcZtZ4NMWklcP5sLWksxUoLAr4tKMxa9EEWhMqBfDCwDwZ8LTJXrKCQlwgCJsdiIY8pCkzqtDLXaEdw",
	"emHZ581RdXPOubCgdMMJChfMyAuEA6VdG6i9PA57QbqW0ZrmdqMwq0VMW5/WSr2pqk9V13AdOwMnCj2r",
	"EOa6yC0cgaiNjvnRN/MmC7FVWQqz8i6e1hF5KdUdCws0NZdnRuZwkOvMHtsFZvZYVG4+KvMULGa85L3D",
	"EXz88ByYs81OFgppnQW8QrMCTSRPaQ+L9+FZuzw5BAvLuczm4YGSHxZZpivloBQrNsxYRfQ7lmYGaew4",
	"yp2u2IwuWZBbiN/La8YVcFj7MqFymQtX15kuVMP0BSxkdtlRssY82R433Sl/vLnN442fwgGft5dhHd60",
	"sqXf7lvX+mXSQGGMR1zuxWIJ1Xc+9I+9Bbg5p/WcfwbfQpLUlQkm2jgFEIVBkXPqT0JeFJUF0XFuAhba",
	"sp/v2WWTS9uedd49HMEnOlQitKREy3IJbYsjUi3liWuWAINHplIWUGTzpsjxmczc6Go299YuOaQ2BczB",
	"iw8PY4b6jStQZb69nPPuwsqZwhwuVuA6KWpU427PFdWyjyXuaLBTdlqWcqnVjOW92UkgOjJUuVQz0hEH",
	"mEsO9J4macEWFEEOXnzUj2tSOZyh+QYW4KcUuqxW7IjoOCDdfSiastzHd7bOFKSDHKeiKhwHdrcmpmi9",
	"nSYNH4dE3TzgeeiFcYHc7gOnd/sdSWlsd5v05nV9R1GijquJwLvSC1FztI7EO5KBFE7J5ZyC0UuwVJJ5",
	"Lqwtwh82u9wn5hsEyclWjmqVwgVmorLY/cY7UadBX6ExMsff+azga0dvn3YPlqd1oyMFoVYhFNi1FnYu",
	"rSgv5KwS9ZO5Tza1ukJj+VO4wKkm8UTqpLBqZPvodvGOuZwShbS4dFjaXV7eL51cNxwRxogV/c199bio",
	"WmZI1eQccUdUGWXji/S4YjVMhUlBFzlaB1NprGtKDG1CyVCiUJT7CgfShb+czsVq3GlF+URKaZhL67RZ",
	"9cyP1BNfu54F1r56L36dV0ZtcmtN6zzrhrUsXlCft922O2xj3J4jLUq9F5YOlsKCFVNkVcgckE2WJeZS",
	"OCxWKcetUPnCi06NAHrh8wjwNSUIg6RJzN8cqXC0tBjr1GQME7/IpEmAJg0vJmmod1OY+HRs0qExVIKs",
	"jFwLRgrBFCahsr0PE8oQOtt4PtPaUkknRcGLw8QJM0NHP2B9b56vpU6/4LFKeN6fl3dQWmHnF6HjNom5",
	"wt9ipyLwj/gPktpy/uOXyTe6hTFINRxBqa0DWS60cUJRR4FzY64najLuWJjQB0+4NpnAga+Ojl5WJyd3",
	"ca2cOQw9D6YLMiwKIo2bHBx1dMFJDHU54GXym3/48a9/+MWv/uvvvvzR375MuiODl8lnlTBCOakwf5mw",
	"v9CVg4Uw1qf1pc6xOJqKjP7sMBG8YwOxEMa92w5ImgT9v7liMQ9tr3lPY00OohvyIvYN6NhlGAxss4Pe",
	"EOE6HW6Sn/qOeKfL/pqIC5FyjSiy2B5R3bqBfjEUUvpVNvM+m2tteUxabuwj7KXfZi/XH+r7SKjca9JM",
	"8ggl5FIWBcskJpGGqI2z175ue1CmQ7MN1D2GG+zgj/p1fBnvDhc6J5vuOJebKJyPJrvEcOafIjFwTNj3",
	"+bUYzdodC9HPdTE05BGq12bLNVzgSocsr20BWpAu9BWlyuWVzCtRFKt4HXD6ESX/yncSeVkykdAFrHej",
	"kGaR/l0FFnd2u+9zcOlNfjnXBbcOl/UEz9AHF9XKekdTj+l4wyRNSEX2G8zxD8bJl//80y9/8Bdffe/P",
	"6x+Pk1/98ntf/eU/MY/P0H1q0bT1kh3Mqs8bculsetpjYYfXdq6rImeOpmBwUXjHTAckNjG3scjr1Pqg",
	"spgJi6OWhjOnDY7O0EW7LZ1t6c+9nEG79s5ssLt8TOHO5Ew93lZ7MEaFVGAhrF1qk3u/htkliJmQyrpe",
	"v+WOrTlnbzJaDr8ZHiynSb3/rgXq51JfICJkBQrDRajXUUlienR+/uys02GjeYhigVoSVx7wHGK1vYC+",
	"e7jnELxDf1QMjfdZt3zJaUu+0FI5b1n0STMu8PX5UtgUtIEl6yoluaXIsRbQ2xpiNr29Xng/CNMIssZD",
	"sNViUUjM/2/AOVjscxUX7eOgMIVE00bTWoM71aqv7Jdz0be7BiJB+bR0jTa3gZ/KOuHEzoqU+kGTTkNi",
	"xGV0W8PwVKhfK79U70TDmiqUCk9W6BpT9lbSxRtpY58g0pu8n4PvlUDul0T1OhusnqH4FvYS8+jC++j7",
	"2zjCZq/BnycdTmk+tTFE5in4fv2RbEPtHp62r2RyZzC48WggHqJaQJJvjNLPOMGnlYcQmybkctt0kvO9",
	"aEc5RA1eJMbWBvAVdyVtW5vchXShs21Zt5qJlDaEVNubr92hxFvi7J64sjTx5O9eYOsx98uuaIWdiVVX",
	"SIG2rWLyML1djIXvVtZB5p99HwQzyJWtzDgbGp6T6tIoIjQOGwI8PoGiWj0cpViWglbFCgSwub9HevyA",
	"6N1c5JFeQkktfn7I9lngi7pRZK63SzP9bpsCueZGz1RHxGCyOVoXol/NjjFDfRgGLVxlRHFUCDWrxAy7",
	"GYvTDAk5ffbY56Z1lSDAVIpH1yEe+UymRo53m8dniNCJBbpLzajMGwDMtCoKyJGEF/pYfvSYPAsUExUE",
	"dUfjh2fJyeiD0UkI/kosZDJO7o5ORneZVW7OWsOz8nkDfwxVfhS/aNBz5MOTE9/5FzCVr0mRdL7aC9YI",
	"n9pW73K84gfQeEDyhdFLiwZmlTC59Z5cTY2wzlSZqwzW8Euux0KJ3Utrko/RBSRnmtStcT7lhycnCTed",
	"lQstZ0GZe8Y/Pf6u9UlK25PZ5jHDDqxQw2hROn61GLG+NuiZ5DkutOEExM1Dvrr+gzRxgrLJ7yR2ZR2W",
	"yStaogNp4Dpax+rXJ1pf2rVZcbUAuQbESqlnx807/3Cbh9baS+ppQ1OJ1JoUtq/AbRN2BJ9w7u2f69RK",
	"90NnpUQ31znMNNoGocFz03qK2oxxFwatRZ99XlTOaTWCc6pMqThtEQQtQstX5rwyqx/lUahckCsIY+QV",
	"RjXlmbbOgy4T70/Qut/X+eqtaUkfhXvdd1tUEVy/QxXtwUkHFLWBlPqRSD0jGZG/uPcWaemjwgeIqZN2",
	"bdauH/BoPaLB2qypbq75SSuctNNVR4NJ+tdp8tFtH6nGVrvO8aZCFpivO4WHHn0NYh2Z3QaTsEDXOwRn",
	"0HqHhnF20JE/ZIPcis9MQ3uUc439sZWVRWOPP5f59XG/tejH6bwal/FdAGWNJuON768bN6M7FWLe7ba2",
	"1DoNuRFLkjQW0xRmRlcLH116Idf1HIh03PS1vr9CowrCgyitjvyxZ+gs3Du5G/MZT6R1T1sm/y/td89B",
	"SNgukqFfp9ulm4LIjLY1zLXT9Gm0iU397i2b+kYlHIxchM78unkQ2wH7Z9t9tNZQWDU7dkLhaTiGUk7+",
	"5MkfegP0baYaA7ylMRnU3HX6GqRXjB8I8e/g44fnKTx6ePqtFP7o04fP/+SQDu6tOO9CC5oaNgw5m+n1",
	"QYCh+M8nfphRqe4mmS7RwoWgfrWtcelO146lWYI+nxx2R7UXSIlaIIdX9gAbXdkOMHVjg+4orEHaHnTw",
	"Mof3m5ulLaqeURs+h5wE3k3ayWkg2ElVIQNEG8ZPpXNEZpfPsPIwi7AnQxAobfBJeeChbw/OdE17oJan",
	"z2P2SfVcTVrQHRUYyh2oZfiOMocuPOqW84YOZmbAeuuOWrqupdxTI851cTNTdNl89FsJv808vg65RMMH",
	"t0tDzSwwKLI5MjxauLkPSTkuCr0qGRWk0btAWS4K5I9W6OBArOHcGp3n2VrfS57zvZS10lTEsE0knB58",
	"qeMr2Te2rtJiB4dZoIu0Ah6qEJ/Ds77VWtd4mdaXsoHKeaXhCZUFSaWvnHGNrKugQEpzLSltCBMgVSc8",
	"+OuCEYv8FhN3FqjdMJB7m2Sf+eV15byvqKn3BNOeTOZmskY/5J91C7Ww8avrNJ539eOeRwpoA/dOPlg7",
	"9ihW0g6e6+2ZFLetdwZsIjwkDbdoSZ9s6sS6UF7M9dr3ceHEQ/4D7idEZr87Rr4DKIMPDkfwVIGtsgyt",
	"TcGi61tI0DFfTvuWitvg830Q/pKrp0ublixJGeoHaYO+DOtZdEPRqqtBbz9g9afqtxyyhjT3rNEFOO8C",
	"JTuDvTWB3L5mE2Ex6bLco45nSLVrh+1z3e3lX51295pPl0ov96j9PITmBvXSp0zQbZRKXhH2rZICE96/",
	"EqghfLjAidfiN2oK+CC+ftHxLevHxxv4pSRNGhQfHe3zhGFQlDTVXf6x7/j3HUwXTrc+snl1G8q3FaMU",
	"z0/bUzPHa16Hucd7oZbPuXZUPTxSe6yYiqbJoooNGPZRq+cMR8O66G93imgsc9EHSPpSK7Qwk1eo+Prx",
	"zAjlwGYGUcHSSIfdFpNFvvPAV7hTf37I5XTapAPcx6Iyx4U29r5YuL76n92e+r+DmD+IPdwr/t/biWtr",
	"F4YlcdmDETF/b0yDyR22jtRrmxXF1mZVOxPe4b+bBzvX+XyS46oL35aplJPF+owEX/NV+IMXv5fC0I3d",
	"7jVdRlXJehiIuR/lHHnjbQewcNSMd7bd4W2hGlsv7+opAxVD60eapuHW3urdTD1etKy7jRCwMe7fMxCw",
	"fPTSX0Vq2Z76Sx0GM+QbHQElAYWwLpoeuOG1ugrWftqriPrsW3vL0juqGwbe5bSXA3l7WfoGZmVATq3y",
	"kutvQCt9Sfg12nsnvTdPRUWwaeicuW1ruXC3Y92ieJ7RNJLYqtc7J2PWEVQ5WEdUStt2ZFHyQHopVsP9",
	"la4+3EKadm8H7iTdAHspDeT60PjzrwvHn6LHNVohpBO0RnObYIvFRH1w9C0G7CqPetgGMrfumwvA6b7D",
	"42EWHDQXJrc55XhKfctSOnn7hrjTAjtv8PCiD0nBvdtsSnWxSiLcJJf5YIp8Q4jiTXzFcYsWjDe4TtuX",
	"/YnO6z/gqJ2UrmHR67F62r77Iw2v+Th4QQ2uT0QZ3gU4NE3u+KKFtuhzBoJihZwhBeGYGHCyrEXa+CNT",
	"FdizDJYlWriSYm2jIxDhfOwDs3ArIBy0Un7/PFwXoHlAMHnat//6CToMd42inbTTPPdoyfcnTY+8+fOW",
	"w2vAlw7kPiyi8IrRxqYbgKLMfT82WMdvB5riC8uOfcQhKd9cF3QmrpqrMzyz9caiVTcSfk2fc/w5//t4",
	"74SlY6jbk5X2xV/eH6CwWkF+s9RnOJd5Z4acRhcJXHo3GZHn6VryY0Grtdf0bsamUl/5EtUvwe+w2ksp",
	"wiWMmm1bYJD8mM+H9FLxTF6EDFRmZOrorN9Yq/pV07RvZYpknBwn168aGjZmeAF9EWChfp4icqnQ2gYz",
	"YEetFAKg8jrdWCnMIRskouSBqR8PnjZzAml9wBOfMf7oEsOD8Mi5xVNFb4U4EyWeSVdPPgfaWR8e1uBI",
	"ftuRnwrXNS1PBcNFea3Ce2TqE2DdZNxgegArDw2Ax8EBqIYzKQh72YI2nO5OmxGER3zwoNJ42CobWv2q",
	"m6l0tsZ+lpVjNCnXFT2CeaC8SW2AvNl9MG88v+H2QqkrN28aBR6C05ti1HQI5V9qdj8APzawqT0aA5Ju",
	"k8r6jU13bIhUmS4Kn5lbvkTrOxdH3YS+m2Cloc8R7W3Q4Dfcqe1mIP7VQwrzDWB4L/vvHaD9JqYYnXcn",
	"NkYxDpYyi99+dvWl387LEcsdb1k6/agPDez0dClD2xwJeKuvqy/nQcG9c/lm2PWr6/8ZAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
