//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for Component.
const (
	ComponentChoice Component = "choice"
	ComponentDetail Component = "detail"
	ComponentForm   Component = "form"
	ComponentTable  Component = "table"
)

// Valid indicates whether the value is a known member of the Component enum.
func (e Component) Valid() bool {
	switch e {
	case ComponentChoice:
		return true
	case ComponentDetail:
		return true
	case ComponentForm:
		return true
	case ComponentTable:
		return true
	default:
		return false
	}
}

// Defines values for DecisionKind.
const (
	DecisionKindAsk    DecisionKind = "ask"
	DecisionKindForm   DecisionKind = "form"
	DecisionKindNone   DecisionKind = "none"
	DecisionKindResult DecisionKind = "result"
)

// Valid indicates whether the value is a known member of the DecisionKind enum.
func (e DecisionKind) Valid() bool {
	switch e {
	case DecisionKindAsk:
		return true
	case DecisionKindForm:
		return true
	case DecisionKindNone:
		return true
	case DecisionKindResult:
		return true
	default:
		return false
	}
}

// Answer The user's answer to a previous `kind: ask` response, resubmitted alongside the original query.
type Answer struct {
	// Param The parameter name the value fills in.
	Param string `json:"param"`

	// Value The chosen value.
	Value string `json:"value"`
}

// Component The widget the frontend renders the result with.
type Component string

// DecisionKind What the planner decided to do about a question.
type DecisionKind string

// ErrorResponse A machine-readable error.
type ErrorResponse struct {
	// Message What went wrong, for humans.
	Message string `json:"message"`
}

// Health The platform's health status.
type Health struct {
	// Status Always "ok" once the process is serving traffic.
	Status string `json:"status"`
}

// InvokeRequest A confirmed call to execute.
type InvokeRequest struct {
	// Args The call's arguments.
	Args map[string]interface{} `json:"args"`

	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`
}

// InvokeResult A call's rendered result.
type InvokeResult struct {
	// Component The widget the frontend renders the result with.
	Component Component `json:"component"`

	// Data The rendered result.
	Data map[string]interface{} `json:"data"`

	// Fields Per-property JSON Schema for `data`'s columns (`table`) or own properties (`detail`) - the same shape as `PlanResult.fields`, built the same way, so a detail turn appended after a form submission shows a Japanese title and enum label exactly like a `/api/plan` result does. Absent when the result has no columns to describe (not an empty object).
	Fields *map[string]interface{} `json:"fields,omitempty"`
}

// Option One candidate value the user can pick, with its Japanese label.
type Option struct {
	// Label Its Japanese label (from x-enum-labels).
	Label string `json:"label"`

	// Value The enum value.
	Value string `json:"value"`
}

// PlanRequest A question, and any answers to a previous disambiguation.
type PlanRequest struct {
	// Answers Answers to a previous `kind: ask` response, if any.
	Answers *[]Answer `json:"answers,omitempty"`

	// Query The question, in Japanese.
	Query string `json:"query"`
}

// PlanResult The planner's decision and, when it was safe to act on immediately, its result. Which of the optional fields are present depends on `kind`: `result` carries `component`, `data`, `source` and, when the response has columns to describe, `fields`; `form` carries `schema`, `initial` and `target`; `ask` carries `question`, `param` and `options`; `none` carries `message`.
type PlanResult struct {
	// Component The widget the frontend renders the result with.
	Component *Component `json:"component,omitempty"`

	// Data The rendered result, when kind is "result".
	Data *map[string]interface{} `json:"data,omitempty"`

	// Fields Per-property JSON Schema for `data`'s columns (`table`) or own properties (`detail`), when kind is "result" - most importantly each enum property's `enumLabels` (value -> Japanese label), so a table cell or form control can show "検品保留" instead of "quarantined" without parsing a model-facing description string apart. Absent when the result has no columns to describe (not an empty object).
	Fields *map[string]interface{} `json:"fields,omitempty"`

	// Initial The values the planner filled in, when kind is "form".
	Initial *map[string]interface{} `json:"initial,omitempty"`

	// Kind What the planner decided to do about a question.
	Kind DecisionKind `json:"kind"`

	// Message A human-readable explanation, when kind is "none".
	Message *string `json:"message,omitempty"`

	// Options The candidate values to choose from, when kind is "ask".
	Options *[]Option `json:"options,omitempty"`

	// Param The parameter the answer will fill in, when kind is "ask".
	Param *string `json:"param,omitempty"`

	// Question The question to show the user, when kind is "ask".
	Question *string `json:"question,omitempty"`

	// Schema The request body's JSON Schema, when kind is "form".
	Schema *map[string]interface{} `json:"schema,omitempty"`

	// Source Which endpoint of which service a call was, or would be, made against.
	Source *Source `json:"source,omitempty"`

	// Target Which endpoint of which service a call was, or would be, made against.
	Target *Source `json:"target,omitempty"`
}

// Source Which endpoint of which service a call was, or would be, made against.
type Source struct {
	// Args The arguments the planner (or the user) supplied.
	Args *map[string]interface{} `json:"args,omitempty"`

	// OperationId The operation id, as declared in that service's contract.
	OperationId string `json:"operationId"`

	// Service The service's name, as configured in ORCHESTRA_SERVICES.
	Service string `json:"service"`
}

// PostInvokeJSONRequestBody defines body for PostInvoke for application/json ContentType.
type PostInvokeJSONRequestBody = InvokeRequest

// PostPlanJSONRequestBody defines body for PostPlan for application/json ContentType.
type PostPlanJSONRequestBody = PlanRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Report whether the platform is up.
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// PostInvoke Execute a confirmed call against a service.
	// (POST /api/invoke)
	PostInvoke(w http.ResponseWriter, r *http.Request)
	// PostPlan Turn a question into a decision and, when safe, its result.
	// (POST /api/plan)
	PostPlan(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostInvoke operation middleware
func (siw *ServerInterfaceWrapper) PostInvoke(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostInvoke(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPlan operation middleware
func (siw *ServerInterfaceWrapper) PostPlan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPlan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/plan", wrapper.PostPlan)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/invoke", wrapper.PostInvoke)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostInvokeRequestObject struct {
	Body *PostInvokeJSONRequestBody
}

type PostInvokeResponseObject interface {
	VisitPostInvokeResponse(w http.ResponseWriter) error
}

type PostInvoke200JSONResponse InvokeResult

func (response PostInvoke200JSONResponse) VisitPostInvokeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostInvoke400JSONResponse ErrorResponse

func (response PostInvoke400JSONResponse) VisitPostInvokeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostInvoke500JSONResponse ErrorResponse

func (response PostInvoke500JSONResponse) VisitPostInvokeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostPlanRequestObject struct {
	Body *PostPlanJSONRequestBody
}

type PostPlanResponseObject interface {
	VisitPostPlanResponse(w http.ResponseWriter) error
}

type PostPlan200JSONResponse PlanResult

func (response PostPlan200JSONResponse) VisitPostPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostPlan500JSONResponse ErrorResponse

func (response PostPlan500JSONResponse) VisitPostPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostPlan501JSONResponse ErrorResponse

func (response PostPlan501JSONResponse) VisitPostPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Report whether the platform is up.
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// PostInvoke Execute a confirmed call against a service.
	// (POST /api/invoke)
	PostInvoke(ctx context.Context, request PostInvokeRequestObject) (PostInvokeResponseObject, error)
	// PostPlan Turn a question into a decision and, when safe, its result.
	// (POST /api/plan)
	PostPlan(ctx context.Context, request PostPlanRequestObject) (PostPlanResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostInvoke operation middleware
func (sh *strictHandler) PostInvoke(w http.ResponseWriter, r *http.Request) {
	var request PostInvokeRequestObject

	var body PostInvokeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostInvoke(ctx, request.(PostInvokeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostInvoke")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostInvokeResponseObject); ok {
		if err := validResponse.VisitPostInvokeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPlan operation middleware
func (sh *strictHandler) PostPlan(w http.ResponseWriter, r *http.Request) {
	var request PostPlanRequestObject

	var body PostPlanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostPlan(ctx, request.(PostPlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostPlanResponseObject); ok {
		if err := validResponse.VisitPostPlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpNjyRH0f4roXpfaWekmp6x/b6X3tNgj+w1i3eZWWMhz4qKroruSk9VZjkza3pbVh8W37iAZFkIyVgg",
	"ccA+IQwSBxA/ZvEH/wJFZFZ3dXf17izyBwdOO1OTFRkfTzzxUftekpu6MZq0d8n4vcTlJdUoP55qNyfL",
	"PxXkcqsar4xOxsmDkqB1ZG85QDkC3gBCY+lamdZBdqV0MQZ0VxlYco3RjlL+qZ3UynsqACujZ04VBL4k",
	"MFbNlMYK3m3JLkaXOkmTxpqGrFckmjRosR5WRP5EnixorIO8a6xagqmqKgdKj5I08YuGknHivFV6lizT",
	"RI4MC8xL40gHIQPvLtPE0rutslQk47ejZp3Ah6vjZvIO5Z6verlz7/B1c1XMyIveU2u0J12AJV2QdfKQ",
	"3VZ5mCtfsjak25rv9TipKEmTgjyqKkmTqbGsR14alfcViXqnyaMjfveowglV4tR4dJz88/FfvvjZx2th",
	"4+SrTz778k9/6KSOkyfvf/jkp588ef+vT97/TZLGy8fJV7/9vTjkFcqVU0Z/X+li18q3Sgz2NRVqTRYK",
	"ylVBBaOmMIAT03pADr7jN/pWBuPX1qG7StJEG30zC/n4OPnqs08///Dne40RaWzyHz//2wdPHn/65PEv",
	"k7S7eZx8+edffPHxR2LmmbXGnkdA79p5CjXmpdJ0ZAkLdhEQvzHagXNNzuGM9rhqTtrD3Bo9S2FqLJRt",
	"jdo9G4qd1CEQvkZY+XJPBlXo2TW3HJRyDJxH37pdvcPzAcurOS4cXCbm6jIBo/OQh401OTkHyoEje630",
	"DLzF6VTlzzYmXjVkyx19ba7onAQwQ2HIjZ4qW1MBOVYVw4weUd562rUI7Sz8WxSK38fqfu/v3raUDlEE",
	"VhWTn521NWnfj81aTRaD/NKdYtjvqwOgihTQcV5UaKkApcEzEsRrOd1ybJK3mPtBMovHhm9Zy2B+lHvE",
	"P7M23nTv/OXXzi4enJ/+5OLs/Ed3Xj67uEF04o2bVqbBnU+LWUiqgZAFjwbioyKy3m688j6Z/q+laTJO",
	"/ud49dQdx/J1vGbdZZoU6PH5ozygzI5dU0VV8ZwIuk/2KFq1gNcv7r0BF6K0JHvGumYS8aqttYODTNg2",
	"OwRjwcw1rB0CB1lg7OwQjiTjHJdAV2JDHOfsfoU6+HwUFM1SmLSq8uvDc1yk4AwgBFHgW6sBm4aNLwCn",
	"niyIajVI/XaOEetKM3eA8Do2qMkReOUrAtQFMAeDcDDQI8x9tYBKXREgZMfYqGOuAllX1gpDbgSnEyec",
	"V5Lu17wSHWiz8gSXC3HkhOBAGw+ogerGLyDE4zB0Dlsx2kLuGkARFkNovRdDtY3Te5pzXxeqQN+1GT42",
	"Q/wHaFR+lUqtBuXd2jvijl00y+Pda+7svAoHU2tq2Chwh8/b2EhgbtjWBDFp1HDIRwFbezm4q+apYAL1",
	"IraKbqtXLJTDeqJmLXa1f4ugw1sDVwyKG2491ZQ1YOHKU+2exR1BdLJcWY3W4oJ/lwZ12Ltrg5VeRe/Z",
	"jg4S9zt4mDAfrLupW1I3pP1iV6chi5SHOTpwOCXxUO7BaFB1TYVCT9UiFYBGZoO3SpWXYKahHW8Cj0Hg",
	"DEDLpZwkRQtiYnAsTFydjSELQjLI0VpFDrKVS7M08lkKmTOtzSnr6RgzXWIkuT6Q6ClkkbluQ8Yk1Lsm",
	"hItlK628wkqEQ+bRzsjzCwKD1fkuQvyGtO3xfLBXbtBGU++N2FFlQyPJd1iJov/Y/6C47QqPL5P/6BK1",
	"V2s4gto4D6pujPWouWIQ5mUgrE6NWw4yfnBXyC+Dg0C/R5ftyclLtMWXh7GmiV6QU1WxalLEpJMyldA1",
	"VzG4TL743Ueff/D4H3//9Zcf/uoyAaWdJyw4HS6Td1u0qL3SVFwmwuw8rTRoHbezCLUpqDqaYs6/9pwI",
	"Id8BG7T+m61waRLx//zAEh+6jeGMx2ZpDHfixe7bg7GrOPg9LQ82hsRlun8IOg0TT2+KesTKYWDXLaU4",
	"YzeUWpfCmNd7pvzNMi6+z0tjnIzh9c496K4ukxtXkNhADFSQG20yOB5xszJXVSUxGYrISqkd2zuue3qt",
	"YqMlB7om5jluCKb+O1wmt8PEFJzTPXJ5HsCFavKsMFyEUxwGqQk3Pb9VowXdQyX6YqXF9hivhL6Kxijt",
	"mUjm8iSOTYBhMJ2jS8FYmJu2KoCLXY0FAc5Qaee/rmF1NaVupPmBsauoH4Jrm6ZSVPx3kBUrd2O9FJad",
	"moGZwOYlOR8d0O1SxjJHOUDQ6FuL1VGFetbirJd8SnsDRhOc3r8TABEjDwi21ZrLR9QvdNHdWrDfuV0Q",
	"QWFyd+wayt2x6WszqguYxjhP26ri4qJmOhYRHti41EeNWQveY5J1wbCT0Qujkxh/jY1KxslLo5PRSwxL",
	"9KUgUQa6crVbiik2uByyFDzy4slJGJAQpuoRFUIEN9oZwZuOjy/kXEHXcoA5i3+fWDN3ZGHWoi2cuEvp",
	"qUXnbZv71lK328pLyq9c8MEGspNXycc1WZp0falY+eLJSSIdn/ax30NOl1xePX7HBZpdE+LTKCbeIIDa",
	"v4pj89tmJHB1bV0jTx3JOTXGShPhy1gltl9gpmOSeDtxC+epTh6yCAmTkhUM69eYoZntrjFXLg4AXT63",
	"TUhhrpceKzNrKeWCKZUzHF7TS4dehqeLjM6wZsBuAnjdAY3gDbomG8/1COo28PMF1ORLU8DMyHXWtLMS",
	"SrIEE8qxdQQIDVnHqWfJMUAEDa33Ro/gQakESnN5RcST7XYYgoQgWeCHrS9J+xhXQGvVNQ0i5b5xPmy0",
	"kkAn5Pz3TLH42lCyueJcbrIWE/3yG4Toxq5uD1BX+7owj3QDyoj54v++Rl02V+57lOnKqrEbpYgDr40f",
	"QLCxW9AtjJx06JWbLnoI5ugv0+T/v22TusW175k3RVVRsU0KZ2G1Dbi99l4Xkyigzw6RDNbswGm3nxt4",
	"8XX37g+C4PD5xsH8WV1Ot6HpdZwjOA1LiZjXB6+ePUjhtbPTV1L44Ztn5z8+5KgF7Yr+viIw+qrwrUfi",
	"g7jyCc+zwxGcamh1/5Lc1ORggvkVoOuWmd50DluJ4OfZYX/+mxAXoKiOSA7LKtO63jpt54J+f73aDx70",
	"dlOHt1efQ9erWFkFhdqYRd9l63EsKuyVbmkEb5i146fKe6mT/c5+EXY38U7ZazAdhmYj+lAL9c5Mp3vU",
	"VkbasXQmXbOuHJgeBPZxIq+sviFG7K8bv2U+7C3i9mRrt4BLt1EqAw17rr+Mm5LPy9F3QiurIb+jEtbh",
	"hW9Xh85ZYHnJQwVXcPQleK7VBTWVWdSyamRcCn/XTUXyaEEeDnBrZ7zCvGxHNsnxgXzM2Gq5cWhhysHZ",
	"2In2yFK48aGYE1pOfvq0L6mhMw2NOu/DOOcYGc6jVzmgc+Sd7BkEHOH/P/CNreWv78fJ8uHq9u17LiK7",
	"xnY2tFVYKE3OrThBvkjymJSMu0Zwme5oHCeUfd4ZxzqiV2J56LpaM5o3/VAQYKBDqa829Koy/WnjSyao",
	"qfKua/jq1ksLyS6hwCdRX/H2rraxzrmbFDohOqOrBdSm9eWqcQz1aaNv7vRAvRAlb0dW3GlIN3SM5XP5",
	"cPmvAQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
