//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RecordKind.
const (
	Compensatory RecordKind = "compensatory"
	Deemed       RecordKind = "deemed"
	OnCall       RecordKind = "on_call"
	Substitute   RecordKind = "substitute"
)

// Valid indicates whether the value is a known member of the RecordKind enum.
func (e RecordKind) Valid() bool {
	switch e {
	case Compensatory:
		return true
	case Deemed:
		return true
	case OnCall:
		return true
	case Substitute:
		return true
	default:
		return false
	}
}

// Error A machine-readable error.
type Error struct {
	// Message What went wrong, for humans.
	Message string `json:"message"`
}

// NewRecord The fields needed to create an attendance record.
type NewRecord struct {
	// Date The date the record applies to (YYYY-MM-DD).
	Date openapi_types.Date `json:"date"`

	// Employee The employee's name.
	Employee string `json:"employee"`

	// Kind What kind of attendance arrangement a record represents.
	Kind RecordKind `json:"kind"`
}

// Record A single attendance record.
type Record struct {
	// Date The date the record applies to (YYYY-MM-DD).
	Date openapi_types.Date `json:"date"`

	// Employee The employee's name.
	Employee string `json:"employee"`

	// Id The record's id.
	Id string `json:"id"`

	// Kind What kind of attendance arrangement a record represents.
	Kind RecordKind `json:"kind"`
}

// RecordKind What kind of attendance arrangement a record represents.
type RecordKind string

// RecordList A page of attendance records.
type RecordList struct {
	// Records The matching attendance records.
	Records []Record `json:"records"`
}

// ListAttendanceRecordsParams defines parameters for ListAttendanceRecords.
type ListAttendanceRecordsParams struct {
	// Kind Restrict the result to records of this kind.
	Kind *RecordKind `form:"kind,omitempty" json:"kind,omitempty"`
}

// CreateAttendanceRecordJSONRequestBody defines body for CreateAttendanceRecord for application/json ContentType.
type CreateAttendanceRecordJSONRequestBody = NewRecord

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAttendanceRecords List attendance records, optionally filtered by kind.
	// (GET /api/attendance/records)
	ListAttendanceRecords(w http.ResponseWriter, r *http.Request, params ListAttendanceRecordsParams)
	// CreateAttendanceRecord Create an attendance record.
	// (POST /api/attendance/records)
	CreateAttendanceRecord(w http.ResponseWriter, r *http.Request)
	// GetAttendanceRecord Get one attendance record by id.
	// (GET /api/attendance/records/{id})
	GetAttendanceRecord(w http.ResponseWriter, r *http.Request, id string)
	// GetAttendanceSpec Return this service's own OpenAPI contract.
	// (GET /openapi.yaml)
	GetAttendanceSpec(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAttendanceRecords operation middleware
func (siw *ServerInterfaceWrapper) ListAttendanceRecords(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAttendanceRecordsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAttendanceRecords(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAttendanceRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateAttendanceRecord(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAttendanceRecord(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttendanceRecord operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttendanceRecord(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttendanceSpec operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceSpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttendanceSpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/openapi.yaml", wrapper.GetAttendanceSpec)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/attendance/records", wrapper.ListAttendanceRecords)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/attendance/records", wrapper.CreateAttendanceRecord)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/attendance/records/{id}", wrapper.GetAttendanceRecord)

	return m
}

type ListAttendanceRecordsRequestObject struct {
	Params ListAttendanceRecordsParams
}

type ListAttendanceRecordsResponseObject interface {
	VisitListAttendanceRecordsResponse(w http.ResponseWriter) error
}

type ListAttendanceRecords200JSONResponse RecordList

func (response ListAttendanceRecords200JSONResponse) VisitListAttendanceRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAttendanceRecordRequestObject struct {
	Body *CreateAttendanceRecordJSONRequestBody
}

type CreateAttendanceRecordResponseObject interface {
	VisitCreateAttendanceRecordResponse(w http.ResponseWriter) error
}

type CreateAttendanceRecord201JSONResponse Record

func (response CreateAttendanceRecord201JSONResponse) VisitCreateAttendanceRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceRecordRequestObject struct {
	Id string `json:"id"`
}

type GetAttendanceRecordResponseObject interface {
	VisitGetAttendanceRecordResponse(w http.ResponseWriter) error
}

type GetAttendanceRecord200JSONResponse Record

func (response GetAttendanceRecord200JSONResponse) VisitGetAttendanceRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceRecord404JSONResponse Error

func (response GetAttendanceRecord404JSONResponse) VisitGetAttendanceRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceSpecRequestObject struct {
}

type GetAttendanceSpecResponseObject interface {
	VisitGetAttendanceSpecResponse(w http.ResponseWriter) error
}

type GetAttendanceSpec200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetAttendanceSpec200ApplicationyamlResponse) VisitGetAttendanceSpecResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAttendanceRecords List attendance records, optionally filtered by kind.
	// (GET /api/attendance/records)
	ListAttendanceRecords(ctx context.Context, request ListAttendanceRecordsRequestObject) (ListAttendanceRecordsResponseObject, error)
	// CreateAttendanceRecord Create an attendance record.
	// (POST /api/attendance/records)
	CreateAttendanceRecord(ctx context.Context, request CreateAttendanceRecordRequestObject) (CreateAttendanceRecordResponseObject, error)
	// GetAttendanceRecord Get one attendance record by id.
	// (GET /api/attendance/records/{id})
	GetAttendanceRecord(ctx context.Context, request GetAttendanceRecordRequestObject) (GetAttendanceRecordResponseObject, error)
	// GetAttendanceSpec Return this service's own OpenAPI contract.
	// (GET /openapi.yaml)
	GetAttendanceSpec(ctx context.Context, request GetAttendanceSpecRequestObject) (GetAttendanceSpecResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAttendanceRecords operation middleware
func (sh *strictHandler) ListAttendanceRecords(w http.ResponseWriter, r *http.Request, params ListAttendanceRecordsParams) {
	var request ListAttendanceRecordsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAttendanceRecords(ctx, request.(ListAttendanceRecordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAttendanceRecords")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAttendanceRecordsResponseObject); ok {
		if err := validResponse.VisitListAttendanceRecordsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAttendanceRecord operation middleware
func (sh *strictHandler) CreateAttendanceRecord(w http.ResponseWriter, r *http.Request) {
	var request CreateAttendanceRecordRequestObject

	var body CreateAttendanceRecordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAttendanceRecord(ctx, request.(CreateAttendanceRecordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAttendanceRecord")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAttendanceRecordResponseObject); ok {
		if err := validResponse.VisitCreateAttendanceRecordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendanceRecord operation middleware
func (sh *strictHandler) GetAttendanceRecord(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAttendanceRecordRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceRecord(ctx, request.(GetAttendanceRecordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceRecord")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAttendanceRecordResponseObject); ok {
		if err := validResponse.VisitGetAttendanceRecordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendanceSpec operation middleware
func (sh *strictHandler) GetAttendanceSpec(w http.ResponseWriter, r *http.Request) {
	var request GetAttendanceSpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceSpec(ctx, request.(GetAttendanceSpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceSpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAttendanceSpecResponseObject); ok {
		if err := validResponse.VisitGetAttendanceSpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fdtb1NHFv4rR7MrAdK1HZZ88rcsQWzEyyJAWkVstJrce+w7cO/MZWZuHCuyhNndNiIg8dKKIpAAFSgU",
	"EdqCKgQUfoxjJ/0X1cxcv8T3OiVV2i/9hIlnzstznueZ4xXiizgRHLlWpLpClB9iTO3HI1IKaT4EqHzJ",
	"Es0EJ1UyAzH1Q8axJJEGdDFCQHOyTDySSJGg1AxtgBiVonXMh/hXSDU0kGtoSMHrHtSEhDCNKVcmim4m",
	"SKpEacl4nbRaHpF4MWUSA1I9N4i6MDgoFs+jr0nLIyexcRp9IYN8zrMhQo1hFCjgiAEGoAX4EqlGoByo",
	"1sgDyn0EaSPk2wmoxuK45hvQYf8q0CSJGCqTYf/8/Px86cSJ0uzsAROyJmRMNam6aB7RTEemh+7LD1vf",
	"P+zdfpzv3yMYJ5Fo4oTs/W/3KeA0xvJo1A+3eo9fdG897F6/VhT4AuMWqr9KrJEq+UtlSIZKxoSKA/SY",
	"OTk+ikFdWSTPdVU0mUljmQHFeD3CP+kA2ASmuj72KWDBaLi52d9hiswMbtejPMZ4Qe1W2SYAiNroSKmU",
	"lNcxNpqn/SlJTCQqU6bpEXkam3ICxBhNASpdVJrp1I7JtIRcUS1kk3hE8P/4NIrIwhCbzafr3dX89Dyy",
	"XDKhSxFdxMjyaFusKtl49/XG+xvE62eukk77Y6f9bad9u3vldfe/10bymYn+v/fs/vbyqqR39WXv7seN",
	"9zcMgVoDkI4zpYs4n9A6jiHkMFF51mdfFPMkptp4cX1CJKYxVp9GDdIaIGeG1czRpF9HnhLmJOM1kS9x",
	"No3j5mhtCuUS87FaVC8cWWZKK1DCSllIP0SlJTWxIImoNtKFkCrLIBoB8iARjGsj8yQyJl6njCtdhjOI",
	"EAhfVVSCvqpsC1WOg/K/+YioZoalzJyaIx5ZQqlc/VPlg+UpS6GUlULG3TCZSiLaPEljq/C1R71LDzbX",
	"H25e/8xiJhLkNGGkSg6Vp8qHzDypDu0UKjRhlWHnlZHR1rGAKKdRp5IrwCWUzTxkcIGLBgft8MqgLYPh",
	"hbAhaOS0eDE19xMqaYwaJXAqpWiozDFVGlkIs2oML3Vfxg4pQ0eL3ZxRhyH1ELPTWQ8eGcRXpHou34rR",
	"o693ysmUy2mIa+7YsolHuEM68yVH21353YJhskoEV05Sf5uacj7ANbqZ2gfDtz1WzivBh6vQpyWyQrdC",
	"2KVGzRWVxjG1VmTCFBzzBvOMmlBjkUaJASw2B3BpWldjGl0uDVhfwmUaJxHaI46vW0+/+vnqD53LN7ee",
	"rHXadzvtJ8QjG++u9O6tdtrr3c/fdtcebV75sfeq3bl8s/flnU571Z0ZNbpOez2L037Qad+woe532v/L",
	"p0+EQlLVMsVP0JKLufHm0taTbyw+iSh00SAwTsCxUaCM7Zow7ygvxRgL2QSlhcQyzGnzuAJTQJVide4A",
	"HRVSAfUP231xnPzEGSUq/XcRNPeMWcNltrXdiw2OrRylD+4xpSfR2e3MQdHCtp3Mh3dern87ZzfvvLOk",
	"u11Aycs3N794tfV8zX67Z2TstNc3frrXW73uQJng45UVFrR+1czpxI3XAyFhemoaGiFyS0VH0JRboy/n",
	"6HgUdQEXd/ThguXSeq15o4ZWywIyTrhR491pHf0DzHYSMzMRTuCmR6anpvesEvfjuKCQk/1HDdCtMw2m",
	"Q/e4sZxEjqIGwQuoYLyI7VYmnfatEUte33r2avP1d2P+7c44bhtWv3mx9fZ5/x3YS7247Jlesp2o3KRx",
	"NFEgZ1AuYdBf/wYLn0851FD7of2zGZ6kvgaxhBL+cfbsKdjPtLVxSKTwUSkPuDC/MmosQhDcCC6k5sEM",
	"mLpwACgPYDFlUQBMK/CpppGopwg1KWJgusj2t+nsTII+2RXH+12PCGhMM4V0Hj5e/0yQz5yaMyttan5C",
	"eUAVzM+cOD7OJ+cxjm3D62ZJ7Ifo4zdKLdVUGmOyYOsw1yZbR36Vt/+ismCaRCaJgbj//9GEqYxIlVRI",
	"a2GQPPeq55YfCDEavM35/OWha2UXSMtb2RHO8bKy6xkMrYXWLwMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
