//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for RecordKind.
const (
	Compensatory RecordKind = "compensatory"
	Deemed       RecordKind = "deemed"
	OnCall       RecordKind = "on_call"
	Substitute   RecordKind = "substitute"
)

// Valid indicates whether the value is a known member of the RecordKind enum.
func (e RecordKind) Valid() bool {
	switch e {
	case Compensatory:
		return true
	case Deemed:
		return true
	case OnCall:
		return true
	case Substitute:
		return true
	default:
		return false
	}
}

// Error A machine-readable error.
type Error struct {
	// Message What went wrong, for humans.
	Message string `json:"message"`
}

// NewRecord The fields needed to create an attendance record.
type NewRecord struct {
	// Date The date the record applies to (YYYY-MM-DD).
	Date string `json:"date"`

	// Employee The employee's name.
	Employee string `json:"employee"`

	// Kind What kind of attendance arrangement a record represents.
	Kind RecordKind `json:"kind"`
}

// Record A single attendance record.
type Record struct {
	// Date The date the record applies to (YYYY-MM-DD).
	Date string `json:"date"`

	// Employee The employee's name.
	Employee string `json:"employee"`

	// Id The record's id.
	Id string `json:"id"`

	// Kind What kind of attendance arrangement a record represents.
	Kind RecordKind `json:"kind"`
}

// RecordKind What kind of attendance arrangement a record represents.
type RecordKind string

// RecordList A page of attendance records.
type RecordList struct {
	// Records The matching attendance records.
	Records []Record `json:"records"`
}

// ListAttendanceRecordsParams defines parameters for ListAttendanceRecords.
type ListAttendanceRecordsParams struct {
	// Kind Restrict the result to records of this kind.
	Kind *RecordKind `form:"kind,omitempty" json:"kind,omitempty"`
}

// CreateAttendanceRecordJSONRequestBody defines body for CreateAttendanceRecord for application/json ContentType.
type CreateAttendanceRecordJSONRequestBody = NewRecord

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAttendanceRecords List attendance records, optionally filtered by kind.
	// (GET /api/attendance/records)
	ListAttendanceRecords(w http.ResponseWriter, r *http.Request, params ListAttendanceRecordsParams)
	// CreateAttendanceRecord Create an attendance record.
	// (POST /api/attendance/records)
	CreateAttendanceRecord(w http.ResponseWriter, r *http.Request)
	// GetAttendanceRecord Get one attendance record by id.
	// (GET /api/attendance/records/{id})
	GetAttendanceRecord(w http.ResponseWriter, r *http.Request, id string)
	// GetAttendanceSpec Return this service's own OpenAPI contract.
	// (GET /openapi.yaml)
	GetAttendanceSpec(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAttendanceRecords operation middleware
func (siw *ServerInterfaceWrapper) ListAttendanceRecords(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAttendanceRecordsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAttendanceRecords(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAttendanceRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateAttendanceRecord(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAttendanceRecord(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttendanceRecord operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttendanceRecord(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAttendanceSpec operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceSpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAttendanceSpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/openapi.yaml", wrapper.GetAttendanceSpec)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/attendance/records", wrapper.ListAttendanceRecords)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/attendance/records", wrapper.CreateAttendanceRecord)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/attendance/records/{id}", wrapper.GetAttendanceRecord)

	return m
}

type ListAttendanceRecordsRequestObject struct {
	Params ListAttendanceRecordsParams
}

type ListAttendanceRecordsResponseObject interface {
	VisitListAttendanceRecordsResponse(w http.ResponseWriter) error
}

type ListAttendanceRecords200JSONResponse RecordList

func (response ListAttendanceRecords200JSONResponse) VisitListAttendanceRecordsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAttendanceRecordRequestObject struct {
	Body *CreateAttendanceRecordJSONRequestBody
}

type CreateAttendanceRecordResponseObject interface {
	VisitCreateAttendanceRecordResponse(w http.ResponseWriter) error
}

type CreateAttendanceRecord201JSONResponse Record

func (response CreateAttendanceRecord201JSONResponse) VisitCreateAttendanceRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceRecordRequestObject struct {
	Id string `json:"id"`
}

type GetAttendanceRecordResponseObject interface {
	VisitGetAttendanceRecordResponse(w http.ResponseWriter) error
}

type GetAttendanceRecord200JSONResponse Record

func (response GetAttendanceRecord200JSONResponse) VisitGetAttendanceRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceRecord404JSONResponse Error

func (response GetAttendanceRecord404JSONResponse) VisitGetAttendanceRecordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceSpecRequestObject struct {
}

type GetAttendanceSpecResponseObject interface {
	VisitGetAttendanceSpecResponse(w http.ResponseWriter) error
}

type GetAttendanceSpec200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetAttendanceSpec200ApplicationyamlResponse) VisitGetAttendanceSpecResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAttendanceRecords List attendance records, optionally filtered by kind.
	// (GET /api/attendance/records)
	ListAttendanceRecords(ctx context.Context, request ListAttendanceRecordsRequestObject) (ListAttendanceRecordsResponseObject, error)
	// CreateAttendanceRecord Create an attendance record.
	// (POST /api/attendance/records)
	CreateAttendanceRecord(ctx context.Context, request CreateAttendanceRecordRequestObject) (CreateAttendanceRecordResponseObject, error)
	// GetAttendanceRecord Get one attendance record by id.
	// (GET /api/attendance/records/{id})
	GetAttendanceRecord(ctx context.Context, request GetAttendanceRecordRequestObject) (GetAttendanceRecordResponseObject, error)
	// GetAttendanceSpec Return this service's own OpenAPI contract.
	// (GET /openapi.yaml)
	GetAttendanceSpec(ctx context.Context, request GetAttendanceSpecRequestObject) (GetAttendanceSpecResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAttendanceRecords operation middleware
func (sh *strictHandler) ListAttendanceRecords(w http.ResponseWriter, r *http.Request, params ListAttendanceRecordsParams) {
	var request ListAttendanceRecordsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAttendanceRecords(ctx, request.(ListAttendanceRecordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAttendanceRecords")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAttendanceRecordsResponseObject); ok {
		if err := validResponse.VisitListAttendanceRecordsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAttendanceRecord operation middleware
func (sh *strictHandler) CreateAttendanceRecord(w http.ResponseWriter, r *http.Request) {
	var request CreateAttendanceRecordRequestObject

	var body CreateAttendanceRecordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAttendanceRecord(ctx, request.(CreateAttendanceRecordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAttendanceRecord")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAttendanceRecordResponseObject); ok {
		if err := validResponse.VisitCreateAttendanceRecordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendanceRecord operation middleware
func (sh *strictHandler) GetAttendanceRecord(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAttendanceRecordRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceRecord(ctx, request.(GetAttendanceRecordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceRecord")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAttendanceRecordResponseObject); ok {
		if err := validResponse.VisitGetAttendanceRecordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendanceSpec operation middleware
func (sh *strictHandler) GetAttendanceSpec(w http.ResponseWriter, r *http.Request) {
	var request GetAttendanceSpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceSpec(ctx, request.(GetAttendanceSpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceSpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAttendanceSpecResponseObject); ok {
		if err := validResponse.VisitGetAttendanceSpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5JfbbhRHE8dfpdTfJwHS7IHgq71zMCIWhyBAiixiRe2Z2p2G6e6hq8frlbUSVpQIJSCBuCBSIiUoIYFI",
	"gRy4iBQCD2N77bxF1D2zx5l1sIRzkyuvvTNV1f/61b/LmyzUMtUKlSXW2mQUxii5/3jGGG3chwgpNCK1",
	"QivWYosgeRgLhTWDPOJrCQK6J+ssYKnRKRor0AeQSMQ7WA7xQcwtdFFZ6BqtOgG0tYE4k1yRi2J7KbIW",
	"I2uE6rB+P2AGb2bCYMRa10ZRV0cP6rXrGFrWD9hF7F7GUJuonPNqjNAWmEQECjHCCKyG0CC3CFwBtxZV",
	"xFWIYHyE8nEibrE6rvsGbDx8FXiaJgLJZTi+srKyUrtwoba0dMKfTdjE1bz7/NX+L48GDx+XzxswlGmi",
	"ezgn2/DbYwSKS5yK+urB4PFPuw8e7d67WxX4hlBemv8bbLMW+19j3PxG0flGLuA59+Ss9KO6ikhBrklV",
	"J+a1YRFIqE6C/xHBxRwS87qPEYhoMtzy0hF0TbhGHbp154SqqN1PrgsAuj3ZQm4MVx2Ubqb5sCsGU4Pk",
	"ynRnRJVJV06EKNEVQNkaWWEz64pyR0JF3GrTYwHT6qOQJwlbHWuz9+TZ7u1y9wK2UXOhawlfw8RzMxWr",
	"xXb++Hbn5X0WDDO32PbW6+2tH7e3Hu5+9mL347sT+VxHPxk8/Xq6vBYb3Hk++PL1zsv7DqD+SKTzgmwV",
	"4ynv4IxCuSZUprz4opoTya3z2s6cSMKipDdDg/VHyrlm9UqYDOsoI+GeFKqtyyUuZVL2JmsjNOsixFZV",
	"vXBmQ5AlIO1HV5swRrKGu1iQJty2tZEQc/IE8QRQRakWyrqxThNn0h0uFNk6XEGESIfUoBRDakyFqsuo",
	"/qGaGKrFcSmLl5ZZwNbRUF5/s36y3vQIZaIWC5U3U1Ca8N5FLv2Ef/7d4NY3e88e7d371GumU1Q8FazF",
	"TtWb9VOun9zGvgsNnorG+OSNidZ2sAKUy2gzowhwHU2vLBncULqrwOZ6FdLWwXGhfQie5LN4M3Pvp9xw",
	"iRYNKG6M7lLhkJQlXsKiGselHY5xrpTD0Wu37KbDQT3W7HJxhoCN4hNrXSsfxc1jaA/KKSjP6cB17/iy",
	"WcBUrnThSzm2h/K71YAZpFQrykfqnWYz9wFlMe+pvyBCf8bGddJqvOq8WSI/6H4QDjmj7hXKpOTeilyY",
	"iseCUT+THrRFYtFgBGu9kVyWd2hmRjdqI+pruJFqQtayJsM3gHn/yRd/3fl15/db+9//4AtMdaWNRZEb",
	"RYXdCjSnoXQXmapJlNr0gKw2WIdl6243EAScSHRUfqJJkivYO+0Xsln6WO5USPZdHfXeWmvH22J/2gyd",
	"jv0SUyffMlPzeMqX0qhqQ5qm6fTB2+tRQLO99Wznz68Gt+/lxc8xvMamiPr/6Hp87ioYgDaw0FyAbozK",
	"I5ODlCnviPUSNmfRVjBzoGFVbGHelJyZjz1JRGwWjEmHOmhv+xdcaR5BxbDMYShgC82Ft1ZJ/l9iRSEX",
	"h+4PmN/7XWHj/BYQJZTPogWtKlBwniGOEuf9p7/tvfi5wLm42+s9LpO5/F5Bs47RcI0ZLS4hV9BGG8b+",
	"z05bw0MLeh0NvHf16iU4Lqx3Q0iNDpEoAKXdttwWCYJWbh5i7ow/EnTjBHAVwVomkgiEJQi55YnuZAht",
	"oyUIW+WeU2NwJcWQHQrB4akn+J5BupK28R3wfopq8dKyW80yicoGwAlWFi+cn213bgE5DOPX3bIzDDHU",
	"b7Lz1COLkq36Otxr8ye7vJL6n0heTJfIJXESD3+fTJiZhLVYg/VXR8lLl2PpEocYk9EVV85fH5tK8QLr",
	"B5sHyjlbVvF6IUN/tf/3AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
